title: the-event.gallery Knowledge Base
description: The public Knowledge Base for the the-event.gallery suite
url: "https://knowledge.the-event.gallery" 
theme: minima
timezone: "Europe/Berlin" # Set your timezone

# Build Settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock


# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji


# Collections
collections:
  learnings:
    output: true
    permalink: /:collection/:path/


# Author
author:
  email: info@the-event.gallery



# # Navigation
# header_pages:
#   - index.md
#   # - about.md
#   # - contact.md

