title: the-event.gallery Knowledge Base
description: The public Knowledge Base for the the-event.gallery suite
url: "https://knowledge.the-event.gallery" 
theme: minima
timezone: "Europe/Berlin" # Set your timezone


# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

# Collections
collections:
  learnings:
    output: true
    permalink: /learnings/:path/  

# # Site Settings
# baseurl: "/TEGKnowledge" 

# # Build Settings
# markdown: kramdown
# theme: minima # Or any other theme you choose
# permalink: /:categories/:title/ # Make URLs more readable and related to the content
# paginate: 10 # Number of posts per page
# exclude:
#   - Gemfile
#   - Gemfile.lock



# # Author
# author:
#   email: info@the-event.gallery



# # Navigation
# header_pages:
#   - index.md
#   # - about.md
#   # - contact.md

